/*
 * CustomWin.java
 *
 * Created on __DATE__, __TIME__
 */

package com.lifeng.window;

import java.util.Date;
import java.util.Vector;

import com.lifeng.db.AccessDb;
import com.lifeng.db.Custom;
import com.lifeng.tools.SysTools;

/**
 * 
 * @author __USER__
 */
public class CustomWin extends javax.swing.JFrame {

	/** Creates new form CustomWin */
	public CustomWin(MainApp fFrame) {
		initComponents();
		this.parentFrame = fFrame;
	}
	public CustomWin(MainApp fFrame,Custom custom) {
		this.parentFrame = fFrame;
		this.custom = custom;
		initComponents();
		
	}
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jTextField7 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setSize(150,250);
		setLocationRelativeTo(getOwner()); 
		this.setTitle("客户添加");
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosed(java.awt.event.WindowEvent evt) {
				formWindowClosed(evt);
			}

			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		jPanel1.setPreferredSize(new java.awt.Dimension(274, 189));
		jPanel1.setLayout(new java.awt.GridLayout(4, 4, 2, 10));

		jLabel1.setText("\u5e8f\u53f7\uff1a");
		jPanel1.add(jLabel1);

		jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
		jTextField1.setText("");
		if(custom!=null)
			jTextField1.setText(custom.getId()+"");
		jTextField1.setEditable(false);
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});
		jPanel1.add(jTextField1);

		jLabel2.setText("\u59d3\u540d\uff1a");
		jPanel1.add(jLabel2);

		jTextField2.setText("");
		if(custom!=null)
			jTextField2.setText(custom.getName());
		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});
		jPanel1.add(jTextField2);

		jLabel3.setText("\u56fd\u5bb6\uff1a");
		jPanel1.add(jLabel3);

		jTextField3.setText("");
		if(custom!=null)
			jTextField3.setText(custom.getNation());
		jPanel1.add(jTextField3);

		jLabel4.setText("\u90ae\u7bb1:");
		jPanel1.add(jLabel4);

		jTextField4.setText("");
		if(custom!=null)
			jTextField4.setText(custom.getMail());
		jPanel1.add(jTextField4);

		jLabel5.setText("\u516c\u53f8\u7f51\u5740\uff1a");
		jPanel1.add(jLabel5);

		jTextField5.setText("");
		if(custom!=null)
			jTextField5.setText(custom.getWeb());
		jPanel1.add(jTextField5);

		jLabel6.setText("电话");
		jPanel1.add(jLabel6);

		jTextField6.setText("");
		if(custom!=null)
			jTextField6.setText(custom.getPhoto());
		jPanel1.add(jTextField6);
		
		jLabel7.setText("\u5907\u6ce8\uff1a");
		jPanel1.add(jLabel7);

		jTextField7.setText("");
		if(custom!=null)
			jTextField7.setText(custom.getRemark());
		jPanel1.add(jTextField7);
		
		jLabel8.setText("创建时间");
		jPanel1.add(jLabel8);

		jTextField8.setText("");
		if(custom!=null)
			jTextField8.setText(custom.getCreate_date());
		jTextField8.setEditable(false);
		jPanel1.add(jTextField8);
		getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

		jButton1.setText("\u4fdd\u5b58");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 400, Short.MAX_VALUE)
						.addGroup(
								jPanel2Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addGap(0, 0,
																Short.MAX_VALUE)
														.addComponent(jButton1)
														.addGap(0, 0,
																Short.MAX_VALUE))));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 50, Short.MAX_VALUE)
						.addGroup(
								jPanel2Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(
												jPanel2Layout
														.createSequentialGroup()
														.addGap(0, 0,
																Short.MAX_VALUE)
														.addComponent(jButton1)
														.addGap(0, 0,
																Short.MAX_VALUE))));

		getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try{
		String id = this.jTextField1.getText();
		String name = this.jTextField2.getText();
		String nation = this.jTextField3.getText();
		String mail = this.jTextField4.getText();
		String web = this.jTextField5.getText();
		String photo = this.jTextField6.getText();
		String remark = this.jTextField7.getText();
		Custom custom = new Custom();
		if(id!=null && !id.equals("")){
			custom.setId(Integer.parseInt(id));
		}
		custom.setName(name);
		custom.setMail(mail);
		custom.setNation(nation);
		custom.setPhoto(photo);
		custom.setCreate_date(SysTools.sf.format(new Date()));
		custom.setRemark(remark);
		custom.setWeb(web);
		AccessDb.saveCustom(custom);
		}catch(Exception e){
			
		}
	}

	private void formWindowClosing(java.awt.event.WindowEvent evt) {
		// TODO add your handling code here:
		this.parentFrame.setEnabled(true);
		Vector vector = AccessDb.getMdbList();
		AccessDb.size = vector.size();
		AccessDb.vector = vector;
		
		this.parentFrame.jTable1.repaint();
	}

	private void formWindowClosed(java.awt.event.WindowEvent evt) {
		// TODO add your handling code here:

	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	/*
	 * public static void main(String args[]) {
	 * java.awt.EventQueue.invokeLater(new Runnable() { public void run() { new
	 * CustomWin().setVisible(true); } }); }
	 */

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	// End of variables declaration//GEN-END:variables
	private javax.swing.JLabel jLabel7;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JTextField jTextField8;
	private MainApp parentFrame;
	private Custom custom;

}